<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.3">
  <Mode>Vertical</Mode>
  <X>20</X>
  <Y>64</Y>
  <VerticalWidth>276</VerticalWidth>
  <VerticalHeight>483</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>00000000</BackgroundColor>
    <BackgroundColor2>00000000</BackgroundColor2>
    <ThinSeparatorsColor>09FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>26FFFFFF</SeparatorsColor>
    <PersonalBestColor>FF16A6FF</PersonalBestColor>
    <AheadGainingTimeColor>FF29CC54</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF70CC89</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC7870</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC3729</BehindLosingTimeColor>
    <BestSegmentColor>FFD8AF1F</BestSegmentColor>
    <NotRunningColor>FF7A7A7A</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <ShadowsColor>80000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAA5DZW50dXJ5IEdvdGhpYwAAL0IF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>True</ShowBestSegments>
    <AntiAliasing>True</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundGradient>Plain</BackgroundGradient>
    <Opacity>1</Opacity>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Splits.dll</Path>
      <Settings>
        <Version>1.3</Version>
        <CurrentSplitTopColor>FF43A2D9</CurrentSplitTopColor>
        <CurrentSplitBottomColor>FF094E76</CurrentSplitBottomColor>
        <VisualSplitCount>8</VisualSplitCount>
        <SplitPreviewCount>1</SplitPreviewCount>
        <DisplayIcons>True</DisplayIcons>
        <ShowThinSeparators>True</ShowThinSeparators>
        <AlwaysShowLastSplit>True</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <ShowSplitTimes>True</ShowSplitTimes>
        <SplitTimesAccuracy>Seconds</SplitTimesAccuracy>
        <BeforeNamesColor>FFFFFFFF</BeforeNamesColor>
        <CurrentNamesColor>FFFFFFFF</CurrentNamesColor>
        <AfterNamesColor>FFFFFFFF</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>FFFFFFFF</BeforeTimesColor>
        <CurrentTimesColor>FFFFFFFF</CurrentTimesColor>
        <AfterTimesColor>FFFFFFFF</AfterTimesColor>
        <OverrideTimesColor>False</OverrideTimesColor>
        <ShowBlankSplits>True</ShowBlankSplits>
        <LockLastSplit>True</LockLastSplit>
        <IconSize>24</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>6</SplitHeight>
        <CurrentSplitGradient>Vertical</CurrentSplitGradient>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <SeparatorLastSplit>True</SeparatorLastSplit>
        <DeltasAccuracy>Tenths</DeltasAccuracy>
        <DropDecimals>True</DropDecimals>
        <OverrideDeltasColor>False</OverrideDeltasColor>
        <DeltasColor>FFFFFFFF</DeltasColor>
        <Comparison>Current Comparison</Comparison>
        <Display2Rows>False</Display2Rows>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Graph.dll</Path>
      <Settings>
        <Version>1.2</Version>
        <Height>120</Height>
        <Width>180</Width>
        <BehindGraphColor>FF732828</BehindGraphColor>
        <AheadGraphColor>FF287334</AheadGraphColor>
        <GridlinesColor>50000000</GridlinesColor>
        <PartialFillColorBehind>19FFFFFF</PartialFillColorBehind>
        <CompleteFillColorBehind>32FFFFFF</CompleteFillColorBehind>
        <PartialFillColorAhead>19FFFFFF</PartialFillColorAhead>
        <CompleteFillColorAhead>32FFFFFF</CompleteFillColorAhead>
        <GraphColor>FFFFFFFF</GraphColor>
        <ShadowsColor>38000000</ShadowsColor>
        <GraphLinesColor>FFFFFFFF</GraphLinesColor>
        <LiveGraph>True</LiveGraph>
        <FlipGraph>False</FlipGraph>
        <Comparison>Current Comparison</Comparison>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.SumOfBest.dll</Path>
      <Settings>
        <Version>1.3</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <Accuracy>Seconds</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.RunPrediction.dll</Path>
      <Settings>
        <Version>1.3</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <Accuracy>Seconds</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Timer.dll</Path>
      <Settings>
        <Version>1.3</Version>
        <TimerHeight>50</TimerHeight>
        <TimerWidth>225</TimerWidth>
        <TimerAccuracy>Hundredths</TimerAccuracy>
        <OverrideSplitColors>False</OverrideSplitColors>
        <ShowGradient>True</ShowGradient>
        <TimerColor>FFAAAAAA</TimerColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <CenterTimer>False</CenterTimer>
      </Settings>
    </Component>
  </Components>
</Layout>